// <auto-generated />
using System;
using Emerald.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emerald.Migrations
{
    [DbContext(typeof(EODbContext))]
    partial class EODbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Emerald.Data.DTOs.CourseDTO", b =>
                {
                    b.Property<string>("SisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CanvasCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanvasName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasState")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catalog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Enrolled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SisId");

                    b.ToTable("CourseRecords");
                });

            modelBuilder.Entity("Emerald.Data.DTOs.FacultyAssignmentsDTO", b =>
                {
                    b.Property<string>("SisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyNo")
                        .HasColumnType("TEXT");

                    b.HasKey("SisId", "FacultyNo");

                    b.ToTable("FacultyAssignmentRecords");
                });

            modelBuilder.Entity("Emerald.Data.DTOs.FacultyDTO", b =>
                {
                    b.Property<string>("FacultyNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CanvasCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanvasName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyNo");

                    b.ToTable("FacultyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
